kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: user20-hello-world
spec:
  containers:
    name: hello-world
    image: 'quay.io/shmuelbd/test:v2'
# set your lab user name
      app: user20-hello-world
  template:
    metadata:
      labels:
# set your lab user name
        app: user20-hello-world
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: hello-world
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
# Update with the image you build in part 1
          image: 'quay.io/shmuelbd/test:v1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10